apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cdb-trading

resources:
  - ../../base

namePrefix: prod-

labels:
  - pairs:
      environment: production

patches:
  - path: replica-patch.yaml
  - path: security-patch.yaml

images:
  - name: your-registry/cdb-ws
    newTag: v1.0.0
  - name: your-registry/cdb-signal
    newTag: v1.0.0
  - name: your-registry/cdb-risk
    newTag: v1.0.0
  - name: your-registry/cdb-execution
    newTag: v1.0.0
  - name: your-registry/cdb-db-writer
    newTag: v1.0.0
