---
apiVersion: v1
kind: Service
metadata:
  name: cdb-signal
  namespace: cdb-trading
  labels:
    app.kubernetes.io/name: claire-de-binare
    app.kubernetes.io/component: signal
spec:
  ports:
  - port: 8001
    targetPort: 8001
    name: http
  selector:
    app: cdb-signal
  type: ClusterIP
