apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cdb-trading

resources:
  - ../../base

namePrefix: dev-

labels:
  - pairs:
      environment: development

patches:
  - path: replica-patch.yaml
  - path: resource-patch.yaml

images:
  - name: your-registry/cdb-ws
    newTag: dev-latest
  - name: your-registry/cdb-signal
    newTag: dev-latest
  - name: your-registry/cdb-risk
    newTag: dev-latest
  - name: your-registry/cdb-execution
    newTag: dev-latest
  - name: your-registry/cdb-db-writer
    newTag: dev-latest
