# Development: Single replica for all services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdb-ws
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdb-signal
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdb-risk
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdb-execution
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdb-db-writer
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
spec:
  replicas: 1
